# -*- coding: utf-8 -*-
"""covid19_var_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HgtWVKtoJE5WlJKtliyW12SC5uYqOF4l
"""

# Import libraries
import pandas as pd
import numpy as np

def import_and_prepare_data():
    # Import new cases data
    df_new_cases = pd.read_csv("https://www.data.gouv.fr/fr/datasets/r/dd0de5d9-b5a5-4503-930a-7b08dc0adc7c", sep=";")
    df_new_cases.index = pd.to_datetime(df_new_cases["jour"])
    df_new_cases = df_new_cases[df_new_cases["cl_age90"]==0]
    df_new_cases = df_new_cases[["P"]].rename({"P": "new_cases"}, axis=1)

    # Import hospital, ICU admissions and deaths data
    df_admissions = pd.read_csv("https://www.data.gouv.fr/fr/datasets/r/6fadff46-9efd-4c53-942a-54aca783c30c", sep=";")
    df_admissions = df_admissions.groupby("jour").sum().reset_index()
    df_admissions.index = pd.to_datetime(df_admissions["jour"])
    df_admissions = df_admissions[["incid_hosp", "incid_rea", "incid_dc"]]

    # Import hospital, ICU admissions and deaths data
    df_hospital = pd.read_csv("https://www.data.gouv.fr/fr/datasets/r/63352e38-d353-4b54-bfd1-f1b3ee1cabd7", sep=";")
    df_hospital = df_hospital.groupby("jour").sum().reset_index()
    df_hospital.index = pd.to_datetime(df_hospital["jour"])
    df_hospital = df_hospital[["hosp", "rea"]]

    # Import data vaccination
    df_vaccination = pd.read_csv("https://www.data.gouv.fr/fr/datasets/r/fa4ad329-14ec-4394-85a4-c5df33769dff", sep=";")
    df_vaccination.index = pd.to_datetime(df_vaccination["jour"])
    df_vaccination["vaccination"] = (df_vaccination["n_cum_dose1"].rolling(window=7).mean().shift(14))
    df_vaccination["vaccination_rappel"] = (df_vaccination["n_cum_rappel"].rolling(window=7).mean().shift(14))
    df_vaccination = df_vaccination[["vaccination", "vaccination_rappel"]].fillna(0)

    # Data merge
    df_dlog = df_new_cases.merge(df_admissions, left_on="jour", right_on="jour")
    df_dlog = df_dlog.merge(df_vaccination, left_on="jour", right_on="jour").fillna(0)
    df_dlog = df_dlog.merge(df_hospital, left_on="jour", right_on="jour").fillna(0)
    df_dlog[df_dlog.columns] = df_dlog[df_dlog.columns].rolling(window=7).mean()

    # dlog compute
    df_dlog = np.log10(df_dlog)
    df_dlog.replace([np.inf, -np.inf], 0, inplace=True)
    df_dlog = df_dlog.dropna()
    df_dlog_all = df_dlog.copy()
    df_dlog = df_dlog["2020-09-01":]

    df_dlog_lastweek = df_dlog[:-7]

    return df_dlog_lastweek, df_dlog, df_dlog_all